version: 1
update_configs:
  - package_manager: "php:composer"
    directory: "/application"
    update_schedule: "daily"
    target_branch: "automated_updates"
    version_requirement_updates: "auto"
  - package_manager: "javascript"
    directory: "/application"
    update_schedule: "daily"
    target_branch: "automated_updates"
    version_requirement_updates: "auto"
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
    target_branch: "automated_updates"
